### ISSUE TITLE
efa.asw.io not working

### ISSUE THREAD

**Issue by fnogatz** [momorientes/metaEFA#2]
Not sure what's the intended use, but the page http://efa.asw.io/ referenced in the `README` is neither working in Firefox nor Chrome.

**Comment by michael-k** [comment]
In Firefox, the (Web) Console says `ReferenceError: wrap is not defined`, which was posted in some slack channel too, iirc.

Is there any error message in Chrome?

**Comment by fnogatz** [comment]
Hm. Seems to be working in Chrome (again?). Not sure what's different from 15 minutes ago :confused:
